# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry_v1.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/telemetry_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/telemetry_v1.proto\x12\x0ctelemetry.v1\"\xa1\x01\n\x0eTelemetryFrame\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x12\n\naltitude_m\x18\x03 \x01(\x02\x12\x13\n\x0b\x62\x61ttery_pct\x18\x04 \x01(\x02\x12*\n\x06status\x18\x05 \x01(\x0e\x32\x1a.telemetry.v1.SystemStatus\x12\x14\n\x0cpayload_hash\x18\x06 \x01(\x0c\"D\n\x14NormalizationRequest\x12\x13\n\x0braw_payload\x18\x01 \x01(\t\x12\x17\n\x0fsource_protocol\x18\x02 \x01(\t\"q\n\x15NormalizationResponse\x12+\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x1c.telemetry.v1.TelemetryFrame\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x19\n\x11sha256_audit_hash\x18\x03 \x01(\t*c\n\x0cSystemStatus\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_HEALTHY\x10\x01\x12\x12\n\x0eSTATUS_WARNING\x10\x02\x12\x13\n\x0fSTATUS_CRITICAL\x10\x03\x32n\n\x10TelemetryService\x12Z\n\x0fNormalizeStream\x12\".telemetry.v1.NormalizationRequest\x1a#.telemetry.v1.NormalizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSTATUS']._serialized_start=391
  _globals['_SYSTEMSTATUS']._serialized_end=490
  _globals['_TELEMETRYFRAME']._serialized_start=43
  _globals['_TELEMETRYFRAME']._serialized_end=204
  _globals['_NORMALIZATIONREQUEST']._serialized_start=206
  _globals['_NORMALIZATIONREQUEST']._serialized_end=274
  _globals['_NORMALIZATIONRESPONSE']._serialized_start=276
  _globals['_NORMALIZATIONRESPONSE']._serialized_end=389
  _globals['_TELEMETRYSERVICE']._serialized_start=492
  _globals['_TELEMETRYSERVICE']._serialized_end=602
# @@protoc_insertion_point(module_scope)
